print("3개 과목의  시험 점수를 차례대로 입력하세요!")
k = int(input("국어: "))
e = int(input("영어: "))
m = int(input("수학: "))
total = k+e+m
print("====================")
print("===시험 점수 결과===")
print( "국어 점수: ", k)
print( "영어 점수: ", e)
print( "수학 점수: ", m)
print("====================")
print("총 합계  점수: ", total)
print("평균 점수: ", round(total/3,2))
print("====================")
